---
- hosts: workers
  become: yes
  become_method: su
  tasks:
    - name: Installing Latest version of Wget
      yum: pkg=wget state=latest
    
    - name: Installing Latest version of Java
      yum: pkg=java-1.7.0-openjdk state=latest
    
    - name: Installing Latest version of Tomcat
      yum: pkg=tomcat state=latest
    
    - name: copy server.xml to Tomcat conf
      copy:
        src:  {{ playbook_dir }}/tomcat_conf/server.xml
        dest: /usr/share/tomcat/conf/server.xml
        remote_src: yes
        owner: root
   
    - name: copy context.xml to Tomcat conf
      copy:
        src:  {{ playbook_dir }}/tomcat_conf/context.xml
        dest: /usr/share/tomcat/conf/context.xml
        remote_src: yes
        owner: root
    
    - name: copy ServerInfo.properties to Tomcat conf
      copy:
        src:  {{ playbook_dir }}/tomcat_conf/org
        dest: /usr/share/tomcat/lib/
        owner: root 
    
    - name: Start Tomcat
      service: name=tomcat state=started enabled=yes
      