- name: Running a play in master node
  hosts: master
  become: yes
  gather_facts: true
  tasks:
    - name: Setting Fact
      set_fact:
       CB_Version: "{{ CB_Version }}"
       ftp_location: "ftp://ftp_cloudblue:Grapple20!@cloudblueftp.eastus.cloudapp.azure.com"

       binary_location: "/home/AutoDeployment"
       master_node_ip: "{{ ansible_host }}"
       master_node_user: "{{ ansible_ssh_user }}"
       master_node_password: "{{ ansible_ssh_pass }}"
       synergy_home: "/usr/share/tomcat/webapps/cloudblue"
       catalina_home: "/usr/share/tomcat"

    - stat:
        path: "{{ binary_location }}/{{ CB_Version }}.iso"
        checksum_algorithm: sha256
      register: stat_result

    - name: Downloading ISO from FTP Location
      get_url:
        url: "{{ ftp_location }}/{{ CB_Version }}.iso"
        dest: "{{ binary_location }}"
      when: stat_result.stat.exists == False
          
    - name: Extracting ISO
      shell: "{{ item }}"
      with_items: 
        - 7z x -y -o"{{ binary_location }}" "{{ binary_location }}/{{ CB_Version }}.iso"
    
    - name: Unzip Portal contents
      unarchive:
        src: "{{ binary_location }}/ISO/Portal/{{ CB_Version }}.zip"
        dest: "{{ binary_location }}/ISO/Portal/"


- name: Running a play in worker node
  hosts: workers
  become: yes
  gather_facts: true
  tasks:
    - name: Stop Tomcat
      command: sh /usr/share/tomcat/bin/shutdown.sh
    # - pause:
        # seconds: 30

    - name: Copy latest Portal from ISO to Remote nodes
      shell: sshpass -p "{{ hostvars['master'].master_node_password }}" scp -r "{{ hostvars['master'].master_node_user }}"@"{{ hostvars['master'].master_node_ip }}":"{{ hostvars['master'].binary_location }}/ISO/Portal/{{ hostvars['master'].CB_Version }}" /home/{{ hostvars['master'].CB_Version }}
      shell: "{{ item }}"
      with_items: 
        - sshpass -p "{{ hostvars['master'].master_node_password }}" scp -r "{{ hostvars['master'].master_node_user }}"@"{{ hostvars['master'].master_node_ip }}":"{{ hostvars['master'].binary_location }}/ISO/Portal/{{ hostvars['master'].CB_Version }}" /home/{{ hostvars['master'].CB_Version }}
        - sshpass -p "{{ hostvars['master'].master_node_password }}" scp -r "{{ hostvars['master'].master_node_user }}"@"{{ hostvars['master'].master_node_ip }}":"{{ hostvars['master'].binary_location }}/ISO/Utilities/CITools" /home/CITools
        - chdir=/home/CITools ls 
    
    - name: Execute the deployment script
      command: sh Deploy_Linux.sh "/home/{{ hostvars['master'].CB_Version }}/webapps/" >> LogUpgrade.log
    
    - name: Start Tomcat
      command: nohup /usr/share/tomcat/bin/startup.sh
      become: true
      become_user: root