---
- hosts: workers
  become: yes
  become_method: su
  vars:
    tomcat_url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32.tar.gz"
    ##java_url: "https://mirror.its.sfu.ca/mirror/CentOS-Third-Party/NSG/common/x86_64/jdk-7u80-linux-x64.rpm"
    java_url: "https://mirror.its.sfu.ca/mirror/CentOS-Third-Party/RCG/common/x86_64/jdk-7u80-linux-x64.rpm"
  tasks:
    - name: Installing Latest version of Wget
      yum: pkg=wget state=latest
    - name: Installing sshpass
      yum: pkg=sshpass state=latest
    - name: Installing rsync
      yum: pkg=rsync state=latest
    
    - name: Checking Java-1.7.80 already downloaded
      stat:
        path: /tmp/jdk-7u80-linux-x64.rpm
      register: stat_result
    
    - name: Downloading Java-1.7.80
      get_url: url={{ java_url }} dest=/tmp
      when: stat_result.stat.exists == False
    
    - name: Installing Java
      shell: rpm -ivh /tmp/jdk-7u80-linux-x64.rpm
      ignore_errors: yes
    
    - name: Checking Tomcat-8.5.32 already downloaded
      stat:
        path: /tmp/apache-tomcat-8.5.32.tar.gz
      register: stat_result
    
    - name: Downloading Tomcat-8.5.32
      get_url: url={{ tomcat_url }} dest=/tmp
      when: stat_result.stat.exists == False
      
    - name: Installing Tomcat
      shell: tar xvzf /tmp/apache-tomcat-8.5.32.tar.gz -C /tmp
       
    - name: Configuring Tomcat
      shell: "{{ item }}"
      with_items: 
        - mkdir -p /usr/share/tomcat
        - rsync -r "/tmp/apache-tomcat-8.5.32/" "/usr/share/tomcat/"
        - rm -rf /usr/share/tomcat/webapps/docs
        - rm -rf /usr/share/tomcat/webapps/examples
        - rm -rf /usr/share/tomcat/webapps/host-manager
        - rm -rf /usr/share/tomcat/webapps/manager
        - rm -rf /usr/share/tomcat/webapps/ROOT
        
    - name: Making changes to catalina.sh file
      lineinfile:
          path: /usr/share/tomcat/bin/catalina.sh
          insertafter: '^#!/bin/sh'
          line: "{{ item.line }}"
      with_items:
          - {line: 'JAVA_OPTS="-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms2048m -Xmx2048m -XX:NewSize=512m -XX:MaxNewSize=512m -XX:PermSize=1024m -XX:MaxPermSize=1024m -XX:+DisableExplicitGC"' }
          - {line: 'export SYNERGY_HOME=/usr/share/tomcat/webapps/cloudblue' }
          - {line: 'export CATALINA_HOME=/usr/share/tomcat' }
          - {line: 'export JAVA_HOME=/usr/java/jdk1.7.0_80' }
    
    - name: Making changes to context.xml file to run Symbolic Link
      lineinfile:
          path: /usr/share/tomcat/conf/context.xml
          insertafter: '^<Context>'
          line: "{{ item.line }}"
      with_items:
          - {line: '<Resources allowLinking="true"/>' }
    
    - file:
        path: /usr/share/tomcat/lib/org/apache/catalina/util
        state: directory
    
    - name: Setting Apache Tomcat Version X
      copy:
        dest: "/usr/share/tomcat/lib/org/apache/catalina/util/ServerInfo.properties"
        content: |
          server.info=Apache Tomcat Version X    
    
    - name: Making changes to Server.xml
      copy: src="server.xml" dest="/usr/share/tomcat/conf/server.xml"
    
    - name: Configure Tomcat to Run as a Service
      copy:
        dest: "/etc/init.d/tomcat"
        content: |
          #!/bin/bash   
          JAVA_HOME=/usr/java/jdk1.7.0_80  
          export JAVA_HOME  
          PATH=$JAVA_HOME/bin:$PATH  
          export PATH  
          CATALINA_HOME=/usr/share/tomcat  
              
          case $1 in  
          start)  
          sh $CATALINA_HOME/bin/startup.sh  
          ;;   
          stop)     
          sh $CATALINA_HOME/bin/shutdown.sh  
          ;;   
          restart)  
          sh $CATALINA_HOME/bin/shutdown.sh  
          sh $CATALINA_HOME/bin/startup.sh  
          ;;   
          esac      
          exit 0
        mode: 0777